[tool.ruff]
line-length = 79
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff]
line-length = 79
select = ["E", "F", "I"]
ignore = ["E203", "W503", "F401", "E501", "F841", "W605"]
exclude = [
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".tox",
    ".venv",
    "_build",
    "buck-out",
    "build",
    "dist",
]

[tool.ruff.isort]
known-first-party = ["myproject"]
profile = "black"
line-length = 79
include_trailing_comma = true
