services:
  kaggle_env_gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    env_file:
      - ../.envrc
    volumes:
      - ..:/workspace
    working_dir: /workspace
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
