services:
  kaggle_env_gpu:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../.envrc
    volumes:
      - $PWD/input:/kaggle/input
      - $PWD:/kaggle/working
    working_dir: /kaggle/working
    tty: true
    container_name: kaggle_project_container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
